#!/bin/bash
# if gdb and cat exc is to be used $1 must be "-a" to recompile gnat rts with -g

set -x

cd $(dirname $0)/build

ADA_COMP_SRCS="-aI../src/ada_comp -aI../src/cli -aI../src/communs -aI../src/par_phase -aI../src/sem_phase -aI../src/expander -aI../src/target_code -aI../src/pretty -I../bin/idl_tools"

gnatmake $ADA_COMP_SRCS -D ./ -o ../bin/T1.exe $1 -v -gnat83 -g -f -aO./ ../src/ada_comp/tlaloc.adb
